### ISSUE TITLE
Dell idRAC is not able to mount iso URL produced by Assisted Image service

### ISSUE THREAD

**Issue by dimka-dk** [openshift/assisted-image-service#183]
As part of automatic bare metal node deployment - Dell nodes are created as BareMetalMachines with BMC ports/user/password specified. 
InfraEnv is created and contains BMH's definitions. MCE starts discovery process, access BMC's endpoint and makes attempt to mount discovery ISO image and boot up the Agent.

produced URL of ISO image is pretty long : (https://assisted-image-service-multicluster-engine.apps.xx.yy..zz.com/byapikey/eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmZyYV9lbnZfaWQiOiI1OTM4MWE5Yi03NmYxLTRjMTItOGI4ZS1hMjFkZjMwOWRjOWMifQ.pmY0sDQbyGxI7-lbvezR2PcC2xqiqZZX3jFLA_uKPGNEzeJqWJV9lrybgzMk9Uee6zKy8k0JCWr5qnOFj-KiqQ/4.14/x86_64/minimal.iso)

iDRAC denies to mount that image with `"Message": "Unable to locate the ISO or IMG image file or folder in the network share location because the file or folder path or the user credentials entered are incorrect.", "MessageId": "IDRAC.2.8.RAC0720",`

Tested things:
- iso image can be downloaded by curl
- shorter ISO image URL can be mounted  - downloaded minimal.iso and placed on http server as short link
- DNS works, no firewall between BMC interface and OCP MCE

Main suspicious is a lenght of URL - can any one advise ?

**Comment by omertuc** [comment]
Maybe as a workaround you can clone the assisted-image-service-multicluster-engine route and name the new one something like `img`, and make sure to use this new route in the assisted-service config

**Comment by carbonin** [comment]
>InfraEnv is created and contains BMH's definitions. MCE starts discovery process, access BMC's endpoint and makes attempt to mount discovery ISO image and boot up the Agent

In this scenario the infraenv URL shouldn't be the one actually getting configured into the BMC.
Ironic caches the ISO and serves a separate, smaller, URL from it's own http server.

Are you indeed using a BMH to provision these hosts or are you putting the infraenv image URL in the BMC directly?

**Comment by carbonin** [comment]
Also a Red Hat support case might be the more appropriate channel for this question.

**Comment by dimka-dk** [comment]
Closing the Issue since after long investigation - it has been discovered that servers have `"RFS.1.IgnoreCertWarning" 'No'` and print misleading message to both Ironic and curl when attempt to mount Ironic's generated iso image..
