### ISSUE TITLE
Outside of openshift org users can't get their PRs merged

### ISSUE THREAD

**Issue by omertuc** [openshift/assisted-image-service#208]
See e.g. #207 

![image](https://github.com/openshift/assisted-image-service/assets/10882062/aa4b981b-6b1f-4b53-be1e-b0e0b4f266ae)

![image](https://github.com/openshift/assisted-image-service/assets/10882062/d9f81235-fe9f-4f32-97e4-b239b57c8668)

No way to get around this Red Hat Konflux thing

**Comment by omertuc** [comment]
This could also be a problem specific to @AmadeusPodvratnik , not sure

**Comment by omertuc** [comment]
[Internal Slack thread](https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1716798951012639)

**Comment by omertuc** [comment]
cc @pastequo

**Comment by pastequo** [comment]
I think the problem was not related to a specific user but rather a specific commit

By reusing the same commit (and therefore same sha), the "old" Konflux check was reused.
By amending his commit, the user was able to remove the Konflux check.

**Comment by omertuc** [comment]
OK great, closing for now, reopen if still relevant
